version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.10.1
    steps:
      - run:
          name: Get GitHub API Status
          command: |
            GH_URL="https://bbquh6t1o7.execute-api.us-west-2.amazonaws.com/stage/consent"
            HTTP_RESPONSE=$(curl -X GET $GH_URL | jq --raw-output '.body' )
            echo $HTTP_RESPONSE
            if [ $HTTP_RESPONSE != "\"YES\"" ]; then
              echo "Error Conflicting Release Dates $HTTP_RESPONSE"
              echo "message"
              circleci-agent step halt
            fi
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Running tests
          command: |
            . venv/bin/activate
            python3 tests.py
      - store_artifacts:
          path: test-reports/
          destination: python_app
